/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_imonitor_collect_util_image_ImageUtil */

#ifndef _Included_com_example_imonitor_collect_util_image_ImageUtil
#define _Included_com_example_imonitor_collect_util_image_ImageUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_imonitor_collect_util_image_ImageUtil
 * Method:    decodeYUV420SP
 * Signature: ([BII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_imonitor_1collect_util_image_ImageUtil_decodeYUV420SP
  (JNIEnv *, jclass, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
